export const menu = [
    { "id": 1, "name": "Doro Wet", "category": "Main", "price": 240, "spicy": true, "image": "./images/doro-wet.jpeg", "description": "A spicy chicken stew cooked slowly with hard-boiled eggs, served on sourdough flatbread." },
    { "id": 2, "name": "Shiro", "category": "Vegetarian", "price": 120, "spicy": false, "image": "./images/shiro.jpeg", "description": "A smooth, thick stew made from ground chickpeas or beans, cooked with garlic, onion, and spices, and eaten with flatbread." },
    { "id": 3, "name": "Kitfo", "category": "Main", "price": 320, "spicy": true, "image": "./images/kitfo.jpeg", "description": "Raw minced beef mixed with spicy butter and chili powder, often served with taba (The black traditional bowl), and eaten either raw or lightly cooked.",},
    { "id": 4, "name": "Tibs", "category": "Main", "price": 280, "spicy": true, "image": "./images/tibs.jpeg", "description": "Sautéed pieces of meat (usually beef or lamb) fried with onions, peppers, and herbs, served hot and eaten with flatbread.",},
    { "id": 5, "name": "Beyaynetu", "category": "Vegetarian", "price": 150, "spicy": false, "image": "./images/beyaynetu.jpeg", "description": "A colorful platter with many small portions of different vegetable stews, lentils, and salads, all served on one big piece of flatbread.",},
    { "id": 6, "name": "Misir Wet", "category": "Vegetarian", "price": 110, "spicy": true, "image": "./images/misir-wet.jpeg", "description": "A spicy red lentil stew cooked with onions, garlic, and berbere spice, served as a hearty vegetarian dish with flatbread.",},
    { "id": 7, "name": "Gomen", "category": "Vegetarian", "price": 90, "spicy": false, "image": "./images/gomen.jpeg", "description": "Cooked greens (like collard greens or kale) chopped and simmered with onions, garlic, and a little spice, served as a side dish.",},
    { "id": 8, "name": "Ayibe", "category": "Side", "price": 70, "spicy": false, "image": "./images/ayibe.jpeg", "description": "A soft, crumbly Ethiopian cheese with a mild, slightly tangy taste, often served as a cool side to balance spicy dishes.",},
    { "id": 9, "name": "Enkulal Firfir", "category": "Breakfast", "price": 110, "spicy": true, "image": "./images/enkulal-firfir.jpeg", "description": "Scrambled eggs mixed with torn pieces of spicy flatbread, cooked with onions and peppers, and served as a hearty breakfast or light meal.",},
    { "id": 10, "name": "Fuul", "category": "Breakfast", "price": 90, "spicy": true, "image": "./images/fuul.jpeg", "description": "A creamy stew of slow-cooked fava beans mixed with onions, garlic, and spices, often eaten for breakfast with flatbread.",},
    { "id": 11, "name": "Genfo", "category": "Breakfast", "price": 130, "spicy": true, "image": "./images/genfo.jpeg", "description": "A thick, sticky porridge made from roasted barley or wheat flour, served in a bowl with a well in the middle filled with spiced butter and chili oil.",},
    { "id": 12, "name": "Chechebsa", "category": "Breakfast", "price": 120, "spicy": true, "image": "./images/chechebsa.jpeg", "description": "Torn pieces of flatbread pan-fried with spiced butter and chili, often mixed with honey or yogurt, and eaten as a breakfast or snack.",},
]